import type { Metadata } from "next";
import { Poppins, Quicksand } from "next/font/google";
import "./globals.css";
import { APIContextProvider } from "./lib/context/ApiContext";
import QueryProvider from "./lib/context/QueryContext";

const poppins = Poppins({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const quicksand = Quicksand({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${quicksand.variable} ${poppins.variable}`}>
      <QueryProvider>
        <APIContextProvider>
          <body className={`font-primary`}>{children}</body>
        </APIContextProvider>
      </QueryProvider>
    </html>
  );
}
